name: Check Folder Changes

on:
  push:
    paths:
      - '2/**' # Replace with the path to your folder
  pull_request:
    paths:
      - '2/**' # Replace with the path to your folder

jobs:
  check_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check folder changes
      run: |
        if [[ -n "$(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} -- '2/')" ]]; then
          echo "Changes detected in folder"
          exit 1
        else
          echo "No changes detected in folder"
        fi
