name: Check Folder Changes

on:
  push:
    paths:
      - 'packages/services/2/**' # Replace with the path to your folder
  pull_request:
    paths:
      - 'packages/services/2/**' # Replace with the path to your folder

jobs:
  check_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check folder changes
      run: |
        cat packages/services/2/test
