name: Check Folder Changes

on:
  push:
    branches:
    - main
    paths:
      - '1/**' # Replace with the path to your folder
      - '2/**' # Replace with the path to your folder

  pull_request:
    paths:
      - '1/**' # Replace with the path to your folder
      - '2/**' # Replace with the path to your folder

jobs:
  check_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check folder changes folder 1
      run: |
        if [[ -n "$(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} -- '1/')" ]]; then
          echo "Changes detected in folder 2"
          exit 1
        else
          echo "No changes detected in folder 1"
        fi

    - name: Check folder changes folder 2
      run: |
        if [[ -n "$(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} -- '2/')" ]]; then
          echo "Changes detected in folder 2"
          exit 1
        else
          echo "No changes detected in folder 2"
        fi
